"""Phase 1 - Data audit of the BrightChamps FDA case dataset.

Audit only: describes what is in the file. No business conclusions.

Usage:
    python3 analysis/phase_01_data_audit.py [path/to/csv]

Writes results/phase_01_data_audit.md (relative to the repo root).
"""

import sys
from datetime import timedelta
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
CANDIDATE_PATHS = [
    ROOT / "data" / "BrightChamps_FDA_Case_Dataset.csv",
    ROOT / "BrightChamps_FDA_Case_Dataset.csv",
]
OUT_PATH = ROOT / "results" / "phase_01_data_audit.md"

EXPECTED_COLUMNS = [
    "lead_id", "lead_source", "geography", "parent_timezone", "created_at",
    "demo_scheduled_at", "rep_assigned", "rep_shift", "follow_up_attempts",
    "demo_joined", "demo_completed", "converted",
]
CATEGORICAL = ["lead_source", "geography", "parent_timezone", "rep_assigned",
               "rep_shift", "demo_joined", "demo_completed", "converted"]
YN_COLS = ["demo_joined", "demo_completed", "converted"]
DATE_COLS = ["created_at", "demo_scheduled_at"]
TS_FORMAT = "%Y-%m-%d %H:%M"


def pct(n, total):
    return f"{n / total * 100:.1f}%" if total else "n/a"


def md_table(frame):
    """Render a DataFrame as a padded GitHub markdown table (no tabulate dependency).

    Columns are padded so the raw file lines up in an editor; numeric and
    percentage columns are right-aligned.
    """
    cols = [str(c) for c in frame.columns]
    rows = [[str(v) for v in row] for row in frame.itertuples(index=False)]
    numeric = [
        bool(rows) and all(r[i] == "" or r[i].replace(",", "").replace(".", "", 1)
                           .rstrip("%").lstrip("-").isdigit() for r in rows)
        for i in range(len(cols))
    ]
    widths = [max(3, len(c), *(len(r[i]) for r in rows)) for i, c in enumerate(cols)]

    def fmt(cells):
        return "| " + " | ".join(
            cell.rjust(w) if num else cell.ljust(w)
            for cell, w, num in zip(cells, widths, numeric)
        ) + " |"

    sep = "| " + " | ".join(
        "-" * (w - 1) + ":" if num else "-" * w for w, num in zip(widths, numeric)
    ) + " |"
    return "\n".join([fmt(cols), sep] + [fmt(r) for r in rows])


def counts_table(series, total, label):
    vc = series.value_counts(dropna=False)
    return md_table(pd.DataFrame({
        label: vc.index.astype(str),
        "count": vc.values,
        "%": [pct(v, total) for v in vc.values],
    }))


def resolve_csv():
    if len(sys.argv) > 1:
        return Path(sys.argv[1])
    for p in CANDIDATE_PATHS:
        if p.exists():
            return p
    sys.exit(f"CSV not found. Looked in: {', '.join(str(p) for p in CANDIDATE_PATHS)}")


def main():
    csv_path = resolve_csv()
    # Read everything as raw strings first so nothing is silently coerced.
    raw = pd.read_csv(csv_path, dtype=str, keep_default_na=False)
    n = len(raw)
    out = []
    w = out.append

    w("# Phase 1 — Data Audit\n")
    w(f"Source file: `{csv_path.relative_to(ROOT) if csv_path.is_relative_to(ROOT) else csv_path}`  ")
    w("Generated by: `analysis/phase_01_data_audit.py` (re-run to reproduce).  ")
    w("Scope: describe the data only. No business interpretation or recommendations.\n")

    # ---------------------------------------------------------------- 1-3
    w("## 1. Shape and columns\n")
    w(f"- Rows (excluding header): **{n:,}**")
    w(f"- Columns: **{raw.shape[1]}**")
    w(f"- Column names match the 12 fields listed in the assignment PDF: "
      f"**{'yes' if list(raw.columns) == EXPECTED_COLUMNS else 'NO'}**")
    w(f"- Any leading/trailing whitespace in column names: "
      f"**{'yes' if any(c != c.strip() for c in raw.columns) else 'no'}**\n")
    w("Exact column names, in file order:\n")
    w("```\n" + "\n".join(f"{i + 1:>2}. {c}" for i, c in enumerate(raw.columns)) + "\n```\n")

    # ---------------------------------------------------------------- 4
    w("## 2. Data types\n")
    w("Raw file is text. The table shows the type each column can be parsed to "
      "without losing values, and what pandas infers by default.\n")
    inferred = pd.read_csv(csv_path).dtypes
    rows = []
    for c in raw.columns:
        s = raw[c][raw[c].str.strip() != ""]
        if c in DATE_COLS:
            ok = pd.to_datetime(s, format=TS_FORMAT, errors="coerce").notna().sum()
            parsed = f"datetime (`{TS_FORMAT}`), {ok}/{len(s)} non-blank parse"
        elif s.str.fullmatch(r"-?\d+").all():
            parsed = "integer"
        elif c in YN_COLS:
            parsed = "categorical flag (Y/N)"
        else:
            parsed = "string / categorical"
        rows.append((c, str(inferred[c]), parsed))
    w(md_table(pd.DataFrame(rows, columns=["column", "pandas default dtype", "parsed as"])) + "\n")

    # ---------------------------------------------------------------- 5
    w("## 3. Missing values\n")
    w("Checked for empty strings, whitespace-only strings, and common null tokens "
      "(`NA`, `N/A`, `null`, `None`, `nan`, `-`).\n")
    null_tokens = {"na", "n/a", "null", "none", "nan", "-"}
    rows = []
    for c in raw.columns:
        blank = (raw[c].str.strip() == "").sum()
        token = raw[c].str.strip().str.lower().isin(null_tokens).sum()
        rows.append((c, blank, pct(blank, n), token))
    w(md_table(pd.DataFrame(rows, columns=["column", "blank", "% blank", "null-like tokens"])) + "\n")

    # ---------------------------------------------------------------- 6
    w("## 4. Duplicates\n")
    dup_rows = raw.duplicated().sum()
    dup_ids = raw["lead_id"].duplicated().sum()
    dup_no_id = raw.drop(columns="lead_id").duplicated().sum()
    w(f"- Fully duplicated rows: **{dup_rows}** ({pct(dup_rows, n)})")
    w(f"- Duplicated `lead_id`: **{dup_ids}** ({pct(dup_ids, n)})")
    w(f"- Rows identical on every column except `lead_id`: **{dup_no_id}** ({pct(dup_no_id, n)})")
    id_ok = raw["lead_id"].str.fullmatch(r"L\d{6}").sum()
    id_num = raw["lead_id"].str[1:].astype(int)
    w(f"- `lead_id` matching pattern `L` + 6 digits: **{id_ok}/{n}**; numeric range "
      f"{id_num.min()}–{id_num.max()} ({id_num.max() - id_num.min() + 1:,} possible values, {n:,} used)\n")

    # ---------------------------------------------------------------- 7
    w("## 5. Categorical columns — unique values\n")
    for c in CATEGORICAL:
        s = raw[c]
        stripped_diff = (s != s.str.strip()).sum()
        w(f"### `{c}` — {s.nunique()} unique values\n")
        w(counts_table(s, n, c) + "\n")
        if stripped_diff:
            w(f"_Values with leading/trailing whitespace: {stripped_diff}_\n")

    w("### Cross-checks between categorical columns\n")
    geo_tz = raw.groupby(["geography", "parent_timezone"]).size().reset_index(name="count")
    geo_multi = geo_tz.groupby("geography").size().gt(1).sum()
    w(f"`geography` → `parent_timezone` mapping ({len(geo_tz)} pairs; geographies with >1 timezone: **{geo_multi}**):\n")
    w(md_table(geo_tz) + "\n")
    rep_shift = raw.groupby(["rep_assigned", "rep_shift"]).size().reset_index(name="leads")
    rep_multi = rep_shift.groupby("rep_assigned").size().gt(1).sum()
    w(f"`rep_assigned` → `rep_shift` mapping (reps appearing on >1 shift: **{rep_multi}**):\n")
    w(md_table(rep_shift) + "\n")
    reps_per_shift = rep_shift.groupby("rep_shift").agg(reps=("rep_assigned", "count"), leads=("leads", "sum"))
    w("Reps and leads per shift:\n")
    w(md_table(reps_per_shift.reset_index()) + "\n")
    ct = pd.crosstab(raw["geography"], raw["rep_shift"])
    w("`geography` × `rep_shift` (lead counts). Shown for completeness; no interpretation at this stage:\n")
    w(md_table(ct.reset_index()) + "\n")

    # ---------------------------------------------------------------- 8
    w("## 6. Date/time ranges\n")
    ts = {c: pd.to_datetime(raw[c].replace("", pd.NA), format=TS_FORMAT, errors="coerce") for c in DATE_COLS}
    rows = []
    for c in DATE_COLS:
        s = ts[c]
        formats = raw[c][raw[c] != ""].str.replace(r"\d", "9", regex=True).unique()
        rows.append((c, s.notna().sum(), str(s.min()), str(s.max()), ", ".join(f"`{f}`" for f in formats)))
    w(md_table(pd.DataFrame(rows, columns=["column", "non-blank", "min", "max", "string shape(s)"])) + "\n")
    w("- Precision: minutes (no seconds, no UTC offset, no timezone suffix).")
    by_month = ts["created_at"].dt.to_period("M").value_counts().sort_index()
    w("- `created_at` by month: " + ", ".join(f"{k}: {v:,} ({pct(v, n)})" for k, v in by_month.items()))
    days = ts["created_at"].dt.date.nunique()
    span = (ts["created_at"].max().normalize() - ts["created_at"].min().normalize()).days + 1
    w(f"- Distinct calendar days with at least one lead created: {days} of {span} in the span")
    daily = ts["created_at"].dt.date.value_counts()
    w(f"- Leads created per day: min {daily.min()}, median {int(daily.median())}, max {daily.max()}")
    after = (ts["demo_scheduled_at"] > ts["created_at"].max()).sum()
    w(f"- `demo_scheduled_at` values later than the last `created_at` ({ts['created_at'].max()}): "
      f"**{after}** ({pct(after, ts['demo_scheduled_at'].notna().sum())} of non-blank)\n")

    lag_h = (ts["demo_scheduled_at"] - ts["created_at"]).dt.total_seconds() / 3600
    lag = lag_h.dropna()
    w("### Gap between `created_at` and `demo_scheduled_at` (hours, rows where both present)\n")
    q = lag.quantile([0, .01, .05, .25, .5, .75, .95, .99, 1])
    w(md_table(pd.DataFrame({"quantile": [f"p{int(i * 100)}" for i in q.index], "hours": q.round(2).values})) + "\n")
    w(f"- Negative gaps (demo before lead created): **{(lag < 0).sum()}**")
    w(f"- Zero gaps: **{(lag == 0).sum()}**")
    w(f"- Gaps under 2 hours: {(lag < 2).sum()} ({pct((lag < 2).sum(), len(lag))}); "
      f"over 7 days: {(lag > 168).sum()} ({pct((lag > 168).sum(), len(lag))})\n")

    # ---------------------------------------------------------------- 10
    w("## 7. Timezone handling\n")
    w("- Neither timestamp column carries a timezone or UTC offset.")
    w("- The assignment PDF does not say which clock the timestamps are recorded in "
      "(UTC, IST, server time, or the parent's local time). **This cannot be determined "
      "from the provided materials.**")
    w("- `parent_timezone` values are all valid IANA names, so local-time conversion is "
      "*possible* once the source clock is assumed.")
    w("- Observation only: in every geography the stored hours are spread almost evenly across "
      "the day (median ~12, IQR ~6–18, close to what a uniform 0–23 spread gives), with no "
      "day/night pattern. The hour of day therefore gives no evidence about which clock is "
      "used.\n")
    rows = []
    for g, grp in raw.assign(ch=ts["created_at"].dt.hour, dh=ts["demo_scheduled_at"].dt.hour).groupby("geography"):
        rows.append((g, grp["parent_timezone"].iloc[0], int(grp["ch"].median()),
                     f"{grp['ch'].quantile(.25):.0f}–{grp['ch'].quantile(.75):.0f}",
                     f"{grp['dh'].median():.0f}", f"{grp['dh'].quantile(.25):.0f}–{grp['dh'].quantile(.75):.0f}"))
    w(md_table(pd.DataFrame(rows, columns=[
        "geography", "parent_timezone", "created hour median", "created hour IQR",
        "demo hour median", "demo hour IQR"])) + "\n")
    w("**Conclusion:** timezone handling *is* needed before any time-of-day or "
      "response-time-by-local-hour analysis, and the source clock must be recorded as an "
      "explicit assumption. Durations between the two timestamps are unaffected as long as "
      "both columns use the same clock (also not stated).\n")

    # ---------------------------------------------------------------- 11
    w("## 8. Y/N flag consistency\n")
    rows = []
    for c in YN_COLS:
        vals = sorted(raw[c].unique())
        non_std = (~raw[c].isin(["Y", "N"])).sum()
        rows.append((c, ", ".join(f"`{v}`" for v in vals), non_std,
                     (raw[c] == "Y").sum(), pct((raw[c] == "Y").sum(), n)))
    w(md_table(pd.DataFrame(rows, columns=["column", "distinct raw values", "non Y/N values", "Y count", "Y %"])) + "\n")

    w("### Logical ordering of funnel flags\n")
    scheduled = ts["demo_scheduled_at"].notna()
    joined, completed, converted = (raw[c] == "Y" for c in YN_COLS)
    checks = [
        ("demo_joined = Y but demo_scheduled_at blank", (joined & ~scheduled).sum()),
        ("demo_completed = Y but demo_joined = N", (completed & ~joined).sum()),
        ("converted = Y but demo_completed = N", (converted & ~completed).sum()),
        ("converted = Y but demo_joined = N", (converted & ~joined).sum()),
    ]
    w(md_table(pd.DataFrame(checks, columns=["rule violated", "rows"])) + "\n")
    combo = (raw.assign(demo_scheduled=scheduled.map({True: "Y", False: "N"}))
             .groupby(["demo_scheduled"] + YN_COLS).size().reset_index(name="count"))
    combo["%"] = [pct(v, n) for v in combo["count"]]
    w("All observed combinations (`demo_scheduled` = `demo_scheduled_at` non-blank):\n")
    w(md_table(combo) + "\n")

    # ---------------------------------------------------------------- 12
    w("## 9. Numeric field: `follow_up_attempts`\n")
    fu_raw = raw["follow_up_attempts"]
    fu = pd.to_numeric(fu_raw, errors="coerce")
    w(f"- Non-numeric values: **{fu.isna().sum()}**")
    w(f"- Non-integer values: **{(fu.dropna() % 1 != 0).sum()}**")
    w(f"- Negative values: **{(fu < 0).sum()}**")
    w(f"- Range: {int(fu.min())}–{int(fu.max())}; mean {fu.mean():.2f}; median {fu.median():.0f}")
    q1, q3 = fu.quantile([.25, .75])
    upper = q3 + 1.5 * (q3 - q1)
    w(f"- Above the 1.5×IQR upper fence ({upper:.1f}): {(fu > upper).sum()} ({pct((fu > upper).sum(), n)}) "
      "— these are the high tail of a discrete count, not necessarily errors\n")
    fu_vc = fu.astype(int).value_counts().sort_index()
    w(md_table(pd.DataFrame({"attempts": fu_vc.index, "count": fu_vc.values,
                             "%": [pct(v, n) for v in fu_vc.values]})) + "\n")
    w("Attempt count against furthest funnel stage reached (lead counts):\n")
    stage = pd.Series("not scheduled", index=raw.index)
    stage[scheduled] = "scheduled, not joined"
    stage[joined] = "joined, not completed"
    stage[completed] = "completed, not converted"
    stage[converted] = "converted"
    order = ["not scheduled", "scheduled, not joined", "joined, not completed",
             "completed, not converted", "converted"]
    fct = pd.crosstab(fu.astype(int), pd.Categorical(stage, categories=order))
    w(md_table(fct.reset_index().rename(columns={"follow_up_attempts": "attempts"})) + "\n")
    w(f"- Rows with 0 follow-up attempts that still joined a demo: {((fu == 0) & joined).sum()} "
      f"({pct(((fu == 0) & joined).sum(), (fu == 0).sum())} of 0-attempt rows). Whether attempts "
      "are counted before or after the demo, and what counts as an attempt, is not stated.\n")

    # ---------------------------------------------------------------- 9
    w("## 10. Invalid or suspicious values — summary\n")
    late = ts["created_at"] >= pd.Timestamp(ts["created_at"].max().date()) - timedelta(days=6)
    late_unsched = (late & ~scheduled).sum()
    early_unsched = (~late & ~scheduled).sum()
    dup_created = raw["created_at"].duplicated(keep=False).sum()
    items = [
        ("Hard errors", "0 found",
         "Checked: unparseable dates, non Y/N flags, negative/non-integer attempts, "
         "duplicate IDs, broken funnel ordering."),
        ("`demo_scheduled_at` blank", f"{(~scheduled).sum():,} ({pct((~scheduled).sum(), n)})",
         "Not stated whether blank means 'never scheduled' or 'not recorded'. None of these rows have demo_joined = Y."),
        ("Scheduled but not joined", f"{(scheduled & ~joined).sum():,} ({pct((scheduled & ~joined).sum(), n)})",
         "Valid state; noted because the reason (no-show, reschedule, cancel) is not in the data."),
        ("`demo_scheduled_at` after last `created_at`", f"{after}",
         "Suggests the column is the demo *slot* time rather than the time the booking was made — not confirmed."),
        ("Minimum created→demo gap", f"exactly {lag.min():.0f}h ({(lag == lag.min()).sum()} rows)",
         f"No gap is shorter than {lag.min():.0f}h. Possible system floor on how soon a demo can be "
         "booked; cannot be confirmed."),
        ("Unscheduled, last 7 days", f"{late_unsched} of {late.sum()} ({pct(late_unsched, late.sum())})",
         f"Compared with {pct(early_unsched, (~late).sum())} unscheduled for earlier leads, so no visible "
         "drop at the scheduling stage. The extraction date is not given, so later stages "
         "(join/complete/convert) for late leads may still be incomplete (right-censoring)."),
        ("Rows sharing a `created_at` value", f"{dup_created}",
         "Expected at minute precision with ~80 leads/day; not an error."),
        ("Timestamps without timezone", "2 columns", "See section 7."),
    ]
    # Long notes go below the table so the table stays narrow and aligned.
    w(md_table(pd.DataFrame([(i + 1, chk, res) for i, (chk, res, _) in enumerate(items)],
                            columns=["#", "check", "result"])) + "\n")
    w("Notes:\n")
    w("\n".join(f"{i + 1}. {note}" for i, (_, _, note) in enumerate(items)) + "\n")

    # ---------------------------------------------------------------- dictionary
    w("## 11. Data dictionary\n")
    w("Meaning is taken only from the assignment PDF's field list and from what the values show. "
      "The table gives the overview; the list below it gives, per column, what is known and what "
      "cannot be determined from the provided materials.\n")
    dd = [
        ("lead_id", "string", "PDF: 'lead id'. Unique per row, format `L` + 6 digits.",
         "Whether IDs are sequential by creation time."),
        ("lead_source", "categorical (6)", "PDF: 'lead source'. Values: " + ", ".join(sorted(raw.lead_source.unique())) + ".",
         "Definition of each source; 'DSA' is not expanded anywhere in the materials. Cost per source (PDF gives only a blended ₹900)."),
        ("geography", "categorical (8)", "PDF: 'geography'. Values are country names.",
         "Whether this is the parent's or child's location, and how it was captured."),
        ("parent_timezone", "categorical (8), IANA tz", "PDF: 'parent timezone'. Maps 1:1 to geography in this file.",
         "Whether it is self-reported or derived from geography."),
        ("created_at", "datetime, minute precision", "PDF: 'created timestamp'. When the lead was created. Range "
         f"{ts['created_at'].min():%Y-%m-%d} to {ts['created_at'].max():%Y-%m-%d}.",
         "Timezone/clock. What event 'created' refers to (form submit, CRM entry, etc.)."),
        ("demo_scheduled_at", "datetime, minute precision; nullable", "PDF: 'demo scheduled timestamp'. "
         f"Blank for {pct((~scheduled).sum(), n)} of leads.",
         "Whether it is the demo slot time or the time the booking was made (values extending past the lead window "
         "suggest slot time). Timezone/clock. Meaning of blank."),
        ("rep_assigned", "categorical (12)", "PDF: 'rep assigned'. Codes AD-01 … AD-12; each rep appears on exactly one shift.",
         "What 'AD' stands for; at which stage the rep is assigned; whether the rep ever changes."),
        ("rep_shift", "categorical (3)", "PDF: 'rep shift'. Values: IST_SHIFT, SEA_SHIFT, US_SHIFT.",
         "Shift working hours; whether shift is assigned per rep or per lead (in this file it is fixed per rep)."),
        ("follow_up_attempts", "integer 0–9", "PDF: 'number of follow-up attempts'.",
         "Channel (call/WhatsApp/email), time window counted, and whether attempts after the demo are included."),
        ("demo_joined", "flag Y/N", "PDF: 'demo joined (Y/N)'.",
         "Whether joining late or for a few minutes counts as Y."),
        ("demo_completed", "flag Y/N", "PDF: 'demo completed (Y/N)'. Only Y when demo_joined = Y.",
         "Definition of 'completed'."),
        ("converted", "flag Y/N", "PDF: 'converted (Y/N)'. Only Y when demo_completed = Y. "
         "PDF assumes ₹60,000 average revenue per converted customer.",
         "Conversion observation window / data extraction date."),
    ]
    w(md_table(pd.DataFrame([(f"`{c}`", t) for c, t, _, _ in dd], columns=["column", "type"])) + "\n")
    for c, _, known, unknown in dd:
        w(f"**`{c}`**")
        w(f"- Known: {known}")
        w(f"- Cannot be determined: {unknown}\n")

    w("## 12. Open questions carried forward (to be handled as written assumptions)\n")
    w("1. Which clock are `created_at` and `demo_scheduled_at` recorded in?")
    w("2. Is `demo_scheduled_at` the demo slot time or the booking time? What does blank mean?")
    w("3. What is the data extraction date, i.e. how long did late-July leads have to progress?")
    w("4. What counts as a follow-up attempt, and over what period?")
    w("5. What are the working hours of each `rep_shift`?")
    w("6. What is 'DSA' as a lead source, and does marketing cost differ by source?")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(out) + "\n")
    print(f"Audited {n:,} rows x {raw.shape[1]} columns from {csv_path}")
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
